Fixed Remote Code Execution Vulnerability
418sec/node-pdf-image pull request #1
Opened 2020-03-10 10:15 UTC by mufeedvh

:gear:  **Fix:**

The `PDFImage()` function doesn't validate the input of `pdfFilePath` input parameter. The `pdfFilePath` parameter accepts the path of the PDF file which is then used in a system command execution which when given without validation will result in a Remote Code Execution (RCE) Vulnerability.

What the fix does is: It validates the `pdfFilePath` input and checks for characters that can be used to concatenate any other system commands.

:question: **How:**

The mitigation is implemented with a Regex (```/;|&|`|\$|\(|\)|\|\||\||!|>|<|\?|\${/g```) check for invalid characters in **_index.js_**

:paperclip: **Proof of Concept (PoC):**

**poc.js** (put inside the **_node-pdf-image_** folder)

```
var PDFImage = require('.').PDFImage;

var pdfImage = new PDFImage('"; sleep 500 #"');
pdfImage.getInfo();
```

:fire: **Fix On Action:**

**OSX:**

    $ brew install imagemagick ghostscript poppler

**Linux (Ubuntu):**

    $ sudo apt-get install imagemagick ghostscript poppler-utils

**Run PoC To Test Fix:**

    $ npm install
    $ node poc.js

:heart:  **After Fix:**

![node-pdf-image-fixed-poc](https://user-images.githubusercontent.com/26198477/76302190-8fee1880-62e5-11ea-9649-22ba553f0f2e.png)

<hr>

### :v: **Fixed!**

<hr>

2020-03-13 11:02 UTC, toufik-airane reviewed
Dear @mufeedvh,

Thank you for your contribution.

The regexp isn't easily readable and so maintainable and especially two parts of the expression.
Can you ease the regular expression or at least document it?

Best regards.

2020-03-13 11:02 UTC, toufik-airane commented on index.js
> +  if (/;|&|`|\$|\(|\)|\|\||\||!|>|<|\?|\${/g.test(pdfFilePath)) {
The regexp isn't easily readable and so maintainable and especially two parts of the expression.
The first part is `|\|\||\|` and the second is `|\${`.

2020-03-13 12:06 UTC, adam-nygate requested changes
Also, it looks like you're duplicating matches for `$` symbols and pipes (matching both `\|\|` and `\|`). Feel free to revise and then we can accept the PR 🙂

2020-03-13 20:02 UTC, mufeedvh commented
Hi,

Check out the revised commit, I just cleaned up the Regex to ```/[`!@#$%^&*()_+\-=\[\]{};':"\\|,<>\/?~]/``` to filter out special characters except `.` to only accept filenames.

2020-03-14 08:58 UTC, toufik-airane requested changes
Dear @mufeedvh,

You are restricting too many characters. Some characters seem not related to a command shell feature.

2020-03-14 08:58 UTC, toufik-airane commented on index.js
> +  var filter_chars = /[`!@#$%^&*()_+\-=\[\]{};':"\\|,<>\/?~]/;
Not all characters could trigger remote code execution.
You've blacklisted some harmful and probably legit one such as _ (underscore), ~ (tilde), etc.

I would only filter these characters, that have potential command shell feature:
;|`$()&<>

2020-03-14 15:54 UTC, mufeedvh commented on index.js
> +  var filter_chars = /[`!@#$%^&*()_+\-=\[\]{};':"\\|,<>\/?~]/;
Oh yeah didn't think about it. I did it in a hurry and was sleepy! 😅

2020-03-14 15:58 UTC, mufeedvh commented
Done, fixed that! :+1:

2020-03-16 10:48 UTC, adam-nygate approved these changes
LGTM 👍

2020-03-16 11:09 UTC, toufik-airane approved these changes

2020-03-20 14:43 UTC, toufik-airane approved these changes

2020-03-20 18:32 UTC, huntr-helper commented
Congratulations @mufeedvh - your fix has been selected! :tada:<br><br>Thanks for being part of the community & helping secure the world\'s open source code.<br>If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting!

2020-03-20 18:32 UTC, merged